[package]
name = "firesim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
log = "0.4.29"
bytemuck = { version = "1.24", features = [ "derive" ] }
cgmath = "0.18.0"
instant = "0.1.13"
